baseURL = 'https://hannaress.github.io/socialDataFinalProject/'
languageCode = 'en-us'
title = 'What Gets The People Going?'
theme = "ananke"
publishDir = "../docs"
[markup.goldmark.renderer]
unsafe = true